services:
  mysql:
    image: mysql:8.0
    container_name: backend_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpw}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-backend}
      MYSQL_USER: ${MYSQL_USER:-backend}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-backendpw}
    ports:
      - "3307:3306" # Exponemos MySQL en 3307 para tu Mac
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-practice:dev
    container_name: backend_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MYSQL_DSN: "${MYSQL_USER:-backend}:${MYSQL_PASSWORD:-backendpw}@tcp(mysql:3306)/${MYSQL_DATABASE:-backend}?parseTime=true"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db_data:
